### PR TITLE
fix: restore with wildcard pattern repetition

### PR DESCRIPTION
**Pull request by meirkl**

### CODE REVIEW

**Comment by meirkl** [comment]
This PR is a draft because I discovered this bug through [pino](https://github.com/pinojs/pino).

The behavior in pino is different than the behavior described in #50. In pino it causes infinite recursion.
The changes in the PR doesn't fix the issue in pino. 

### Pino reproduction

```js
const pino = require('pino');

const logger = pino({
  redact: { paths: ['*.d', '*.*.d', '*.*.*.d'] },
});

const obj = {
  x: { c: { d: 'hide me', e: 'leave me be' } },
  y: { c: { d: 'and me', f: 'I want to live' } },
  z: { c: { d: 'and also I', g: 'I want to run in a stream' } },
};

logger.info(obj);
console.log(obj);

```

**Comment by mcollina** [comment]
This seems correct

**Comment by meirelementor** [comment]
It doesn't fix https://github.com/pinojs/pino/issues/1513

**Comment by meirkl** [comment]
@mcollina What about [this](https://github.com/davidmarkclements/fast-redact/issues/50#issuecomment-1210647065)?

**Comment by mcollina** [comment]
@meirkl send a PR.

**Comment by meirelementor** [comment]
> @meirkl send a PR.

You want me to add [this](https://github.com/davidmarkclements/fast-redact/issues/50#issuecomment-1210647065) to the PR?

**Comment by meirkl** [comment]
> @meirkl send a PR.

You want me to add [this](https://github.com/davidmarkclements/fast-redact/issues/50#issuecomment-1210647065) to the PR?

**Comment by mcollina** [comment]
I don't understand the status of this. We want the problem in pino resolved, right? Make it so ;).

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]

**Pull request merged**
